### ISSUE TITLE
Move this repo to VirtualLab?

### ISSUE THREAD

**Issue by mizzao** [ldworkin/meteor-prisoners-dilemma#7]
Hey @ldworkin,

Would you mind transferring this project to [VirtualLab](https://github.com/VirtualLab/)? I just moved CrowdMapper there as well. It would be nice to have all the related projects in the same place for visibility purposes.

It has the added benefit that the right side of your profile at https://github.com/ldworkin will look very ordered and cool :)

**Comment by ldworkin** [comment]
Yes agreed, done!
